name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace 'main' with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node.js version you're using locally

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run deploy script
      - name: Deploy to GitHub Pages
        run: npm run deploy
